version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api/database.db:/workspace/api/database.db
    environment:
      - PYTHONUNBUFFERED=1

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
      - PYTHONUNBUFFERED=1
    depends_on:
      - api
